### ISSUE TITLE
Improve PasswordHashing Class

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#321]
## Tasks:
- [x] Add `random_compat`: 2996f96ddfd4f47f07a460e2ed64ffc5d352a43f
- [x] Replace `openssl_random_pseudo_bytes` with `random_bytes`: 2996f96ddfd4f47f07a460e2ed64ffc5d352a43f
- [x] Add `genRandomInt` function based on `random_int`: 2996f96ddfd4f47f07a460e2ed64ffc5d352a43f
- [x] Add options to choose chars for password generating: 9cc71321bbcd8cb500d7b0962da4e04feda3dcca

## Background Info:
**random_compat lib reprository:** https://github.com/paragonie/random_compat
**Blog Posts:**
- https://paragonie.com/blog/2015/07/how-safely-generate-random-strings-and-integers-in-php
- https://paragonie.com/blog/2015/07/common-uses-for-csprngs-cryptographically-secure-pseudo-random-number-generators
