### ISSUE TITLE
GDPR (DSGVO)

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#754]
General Data Protection Regulation (Datenschutz-Grundverordnung)

Dinge die Admidio für die Nutzer unterstützen sollte:
- [ ] Recht auf Auskunft (#695)
- [ ] Recht auf Übertragbarkeit (#695)
- [ ] Recht auf Löschung
- [ ] Recht auf Korrektur
- [ ] Einwilligung zur Verarbeitung von personenbezogenen Daten
- [ ] Ausdrückliche Einwilligung zur Verarbeitung von sensiblen Daten
- [ ] ...

Dinge die Admidio für die Administratoren unterstützen sollte:
- [ ] Hinweisfelder auf Art des Datenfeldes (personenbezogen, sensibel)
- [ ] ...

Dinge die Admidio für den Schutz der Daten umsetzen sollte:
- [ ] Verschlüsselung der Daten (#230)
- [ ] Zwei-Faktor-Authentifizierung
- [ ] Automatische Löschung aller Daten nach Beendigung der Mitgliedsschaft
- [ ] ...

**Comment by exwima** [comment]
Weiterer Wunsch: 
Im Bereich "Einstellungen" bei "Registrierung" ein **Textfeld "Registrierungshinweis"** oder ähnliches einbauen, dass man individuell befüllen kann. Dieser Text soll dann auf der Registrierungsseite /profile_new.php?new_user=2 automatisch über dem Registrierungsformular angezeigt werden.
Dann könnte man z.B. die Info ablegen, dass Admidio nur für Mitglieder zugänglich ist und daher das Konto erst nach Prüfung freigeschaltet wird. Und man könnte v.a. schon an dieser Stelle wichtige Hinweise zum Datenschutz angeben, nämlich für wen die bei der Registrierung eingegebenen Daten sichtbar sein werden.

**Comment by exwima** [comment]
Wunsch bezüglich der Einwilligungserklärung:
Es wäre gut, wenn die nötige **Einwilligung zur Datenverarbeitung** bei der Registrierung mit erhoben ("Häkchen als Pflichtfeld, Text der Einwilligung, Hinweis auf die Datenschutzerklärung") und im Profil gespeichert würde.

**Comment by ian76g** [comment]
zu: "Automatische Löschung aller Daten nach Beendigung der Mitgliedsschaft"

Unser Vereinsjahr geht immer von April bis April, die Mitgliedschaft aber immer im Jahreskalender (also Januar -Dez.)

Wir handhaben das im Moment so, dass Löschen/Austritt wie bisher in Admidio einfach die Mitgliedschaft beendet wird (reguläre Kündigung endet 31.12., sofortige Kündigung eben sofort).

Zur Jahreshauptversammlung (April) wird dann alles nicht mehr aktive gelöscht (Austritt in der Vergangenheit) und der neue Vorstand arbeitet dann nur mit den noch "aktiven" Datensätzen.

Ich denke dass zur ordentlichen Führung des Vereins (inkl. Kassenprüfung) auch die Mitgliederdaten noch in der Datenbank sein sollten, nach der Kassenprüfung kann dann die Altlast gelöscht werden. Vorher wäre echt blöd.

**Comment by Fasse** [comment]
@exwima Für deinen ersten Hinweis hab ich jetzt mal einen separaten Issue erzeugt #784 das sollte einfach zu integrieren sein und ist sinnvoll. Habt ihr ggf. Vorschläge für einen initialen Text, dieser sollte sehr allgemein sein und berücksichtigen, dass Admidio auch außerhalb Europas genutzt wird.

**Comment by Fasse** [comment]
@exwima zu deinem 2. Punkt habe ich jetzt auch einen Issue #787 erstellt.
